# Generated by Django 4.2.8 on 2026-06-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('month_num', models.IntegerField(default=1)),
                ('year_num', models.IntegerField(default=1405)),
            ],
        ),
    ]
