# Generated by Django 4.2.8 on 2026-06-12 09:51

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'مدیران سایت',
                'verbose_name_plural': 'مدیران سایت',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='جشنواره فروش', max_length=255, verbose_name='عنوان هزینه')),
                ('pay_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ')),
                ('amount', models.IntegerField(default=0, verbose_name='مقدار (تومان)')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.owner')),
            ],
            options={
                'verbose_name': 'هزینه\u200cها',
                'verbose_name_plural': 'هزینه\u200cها',
            },
        ),
    ]
