# Generated by Django 4.2.8 on 2026-06-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_owner_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'verbose_name': 'حساب\u200cهای ماهانه', 'verbose_name_plural': 'حساب\u200cهای ماهانه'},
        ),
        migrations.AddField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
