# Generated by Django 4.2.8 on 2026-04-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='YourEmail@gmail.com', max_length=255),
        ),
    ]
