# Generated by Django 4.2.8 on 2025-05-03 17:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
