# Generated by Django 4.2.8 on 2025-05-04 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_product_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255, verbose_name='گروه سنی')),
            ],
            options={
                'verbose_name': 'گروه\u200cهای سنی',
                'verbose_name_plural': 'گروه\u200cهای سنی',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.agecategory', verbose_name='گروه سنی'),
        ),
    ]
