# Generated by Django 4.2.8 on 2025-05-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_agecategory_product_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='show_ages',
            field=models.BooleanField(default=False, verbose_name='نمایش گروه\u200cهای سنی'),
        ),
    ]
