# Generated by Django 4.2.8 on 2025-05-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_store_show_ages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_original',
            field=models.BooleanField(default=False, verbose_name='کالای اصلی'),
        ),
    ]
