# Generated by Django 4.2.8 on 2025-05-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_product_is_original'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postthumbnail',
            options={'ordering': ('-created',), 'verbose_name': 'تصویر شاخص پست', 'verbose_name_plural': 'تصویر شاخص پست'},
        ),
        migrations.AddField(
            model_name='store',
            name='default_canonical',
            field=models.CharField(default='https://Liatoy.com/', max_length=255),
        ),
    ]
