# Generated by Django 4.2.8 on 2025-05-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_postthumbnail_options_store_default_canonical'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
