# Generated by Django 4.2.8 on 2025-05-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_tag_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agecategory',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
