# Generated by Django 4.2.8 on 2025-05-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_agecategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricerange',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
