# Generated by Django 4.2.8 on 2025-05-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_brand_slug_pricerange_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductFilter',
        ),
    ]
