# Generated by Django 4.2.8 on 2025-05-27 06:26

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_delete_productfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_name', models.CharField(max_length=255, verbose_name='نام شبکه')),
                ('link', models.CharField(max_length=255, verbose_name='لینک حساب')),
                ('icon', models.ImageField(default='media/11.png', upload_to=shop.models.logo_upload_path, verbose_name='آیکون')),
            ],
        ),
    ]
