# Generated by Django 4.2.8 on 2025-05-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_alter_socialaccount_options_socialaccount_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='store',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='store',
            name='telegram',
        ),
    ]
