# Generated by Django 4.2.8 on 2025-06-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_remove_store_instagram_remove_store_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات برند'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_og_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات OpenGrapg'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_og_title',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان OpenGrapg'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_tc_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کارت توییتر'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_tc_title',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان کارت توییتر'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات دسته بندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_og_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات OpenGrapg'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_og_title',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان OpenGrapg'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_tc_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کارت توییتر'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_tc_title',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان کارت توییتر'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات تگ'),
        ),
        migrations.AddField(
            model_name='tag',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا'),
        ),
        migrations.AddField(
            model_name='tag',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='tag',
            name='meta_og_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات OpenGrapg'),
        ),
        migrations.AddField(
            model_name='tag',
            name='meta_og_title',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان OpenGrapg'),
        ),
        migrations.AddField(
            model_name='tag',
            name='meta_tc_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کارت توییتر'),
        ),
        migrations.AddField(
            model_name='tag',
            name='meta_tc_title',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان کارت توییتر'),
        ),
    ]
