# Generated by Django 4.2.8 on 2025-06-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_brand_description_brand_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='meta_og_description',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='meta_og_title',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='meta_tc_description',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='meta_tc_title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_og_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_og_title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_tc_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_tc_title',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='meta_og_description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='meta_og_title',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='meta_tc_description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='meta_tc_title',
        ),
    ]
