# Generated by Django 4.2.8 on 2025-06-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_remove_brand_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='identity',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
