# Generated by Django 4.2.8 on 2025-06-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_store_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='identity',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='هویت سایت'),
        ),
    ]
