# Generated by Django 4.2.8 on 2025-06-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_alter_store_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='title',
            field=models.CharField(default='جشنواره فروش', max_length=255, verbose_name='عنوان کد تخفیف'),
        ),
    ]
