# Generated by Django 4.2.8 on 2025-06-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_coupon_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders_num',
            field=models.IntegerField(default=0, verbose_name='تعداد سفارشات تا کنون'),
        ),
    ]
