# Generated by Django 4.2.8 on 2025-06-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_customer_orders_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashback',
            options={'verbose_name': 'پاداش\u200cها', 'verbose_name_plural': 'پاداش\u200cها'},
        ),
        migrations.RemoveField(
            model_name='cashback',
            name='const',
        ),
        migrations.RemoveField(
            model_name='cashback',
            name='repetation',
        ),
        migrations.AddField(
            model_name='cashback',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='cashback',
            name='order_level',
            field=models.IntegerField(default=0, verbose_name='مرتبه سفارش'),
        ),
        migrations.AlterField(
            model_name='cashback',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
    ]
