# Generated by Django 4.2.8 on 2025-06-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_alter_cashback_options_remove_cashback_const_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_cashback',
            field=models.BooleanField(default=False, verbose_name='کش\u200cبک'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_times',
            field=models.IntegerField(default=0, verbose_name='تعداد مصرف'),
        ),
    ]
