# Generated by Django 4.2.8 on 2025-08-29 08:58

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='favicon',
            field=models.ImageField(default='media/11.png', null=True, upload_to=shop.models.upload_path, verbose_name='فاویکن'),
        ),
    ]
