# Generated by Django 4.2.8 on 2025-08-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_store_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slogan',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='شعار فروشگاه'),
        ),
    ]
