# Generated by Django 4.2.8 on 2025-08-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_store_slogan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('priority', 'name'), 'verbose_name': 'دسته\u200cبندی\u200cهای محصولات', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای محصولات'},
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
