# Generated by Django 4.2.8 on 2025-11-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_alter_category_options_category_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'verbose_name': 'محصولات', 'verbose_name_plural': 'محصولات'},
        ),
    ]
