# Generated by Django 4.2.8 on 2025-11-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
