# Generated by Django 4.2.8 on 2025-12-08 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_product_video_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='توضیحات برند'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='توضیحات دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='توضیحات برچسب'),
        ),
    ]
