# Generated by Django 4.2.8 on 2025-12-08 11:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='short_description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='توضیحات مختصر برند'),
        ),
    ]
