# Generated by Django 4.2.8 on 2025-12-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_brand_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='shop.brand', verbose_name='برند')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
