# Generated by Django 4.2.8 on 2025-12-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_brandfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default='media/11.png', null=True, upload_to='brands/'),
        ),
    ]
