# Generated by Django 4.2.8 on 2025-12-08 15:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_alter_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='media/11.png', null=True, upload_to='category/'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='توضیحات کوتاه دسته\u200cبندی'),
        ),
        migrations.CreateModel(
            name='CategoryFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='shop.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
