# Generated by Django 4.2.8 on 2025-12-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_category_image_category_short_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryfaq',
            old_name='brand',
            new_name='category',
        ),
    ]
