# Generated by Django 4.2.8 on 2025-12-10 15:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_rename_brand_categoryfaq_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات برند'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات مختصر برند'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات کوتاه دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات برچسب'),
        ),
    ]
