# Generated by Django 4.2.8 on 2025-12-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_alter_brand_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default='media/11.png', upload_to='brands/'),
        ),
    ]
