# Generated by Django 4.2.8 on 2026-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_alter_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='قیمت خرید'),
        ),
    ]
