# Generated by Django 4.2.8 on 2026-05-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0071_product_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
