# Generated by Django 4.2.8 on 2026-06-11 17:08

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0073_category_meta_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تگ\u200cهای وبلاگی',
                'verbose_name_plural': 'تگ\u200cهای وبلاگی',
                'ordering': ('-created_date',),
            },
        ),
        migrations.RemoveField(
            model_name='postthumbnail',
            name='post',
        ),
        migrations.DeleteModel(
            name='UploadedImages',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_og_description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_og_title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_tc_description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_tc_title',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='لیاتوی', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(default='media/11.png', upload_to=shop.models.thumbnail_upload_path, verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا'),
        ),
        migrations.DeleteModel(
            name='PostThumbnail',
        ),
        migrations.AddField(
            model_name='blogpostfaq',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.blogpost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='shop.blogtag'),
        ),
    ]
