# Generated by Django 4.2.8 on 2026-06-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0075_alter_order_options_alter_order_status_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_og_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_og_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_tc_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_tc_title',
        ),
    ]
