# Generated by Django 4.2.8 on 2026-07-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0076_remove_product_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
